language: cpp
jobs:
  include:
# Disabled since OpenAL can't be built with clang 7 and libstdc++
#    - os: linux
#      dist: bionic
#      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
#    - os: linux
#      dist: focal
#      compiler: clang
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode10.2
      compiler: clang

addons:
  apt:
    packages:
      - ccache
      - python3-pip
      - libgl1-mesa-dev
      - libxrandr-dev
      - libxaw7-dev
  homebrew:
    packages:
      - xz
      - ccache
      - python3
env:
  global:
    - CONAN_V2_MODE=1
    - CONAN_REVISIONS_ENABLED=1
    - CONAN_SCM_TO_CONANDATA=1

cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
before_install:
  - sudo pip3 install --upgrade pip wheel setuptools jinja2
  - sudo pip3 install --upgrade conan
  - conan --version
  - conan user
  - conan remote add worldforge https://artifactory.ogenvik.org/artifactory/api/conan/conan
script:
  - set -e
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" == "clang++" ]]; then
      echo "Setting libc to use C++11 features"
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - |
    if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
      conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
    else
      echo "Could not find Artifactory password and login name"
      exit 1
    fi
  - conan remove "sigc++/*" --force
  - conan create sigc++ worldforge/stable -pr default --build missing && conan create sigc++ worldforge/stable -pr default
  - conan remove "libcurl/*" --force
  - conan create libcurl worldforge/stable -pr default --build missing && conan create libcurl worldforge/stable -pr default
  - conan remove "tinyxml/*" --force
  - conan create tinyxml worldforge/stable -pr default --build missing && conan create tinyxml worldforge/stable -pr default
  - conan remove "bullet3/*" --force
  - conan create bullet3 worldforge/stable -pr default --build missing && conan create bullet3 worldforge/stable -pr default
  - conan remove "alut/*" --force
  - conan create alut worldforge/stable -pr default --build missing && conan create alut worldforge/stable -pr default
  - conan remove "freeimage/*" --force
  - conan create freeimage worldforge/stable -pr default --build missing && conan create freeimage worldforge/stable -pr default
  - conan remove "sdl2/*" --force
  - conan create sdl2 worldforge/stable -pr default --build missing && conan create sdl2 worldforge/stable -pr default
  - conan remove "libxdg-basedir/*" --force
  - conan create libxdg-basedir worldforge/stable -pr default --build missing && conan create libxdg-basedir worldforge/stable -pr default
  - conan remove "lua/*" --force
  - conan create lua worldforge/stable -pr default --build missing && conan create lua worldforge/stable -pr default
  - conan remove "tolua++/*" --force
  - conan create tolua++ worldforge/stable -pr default --build missing && conan create tolua++ worldforge/stable -pr default
  - conan remove "pcre/*" --force
  - conan install pcre/8.44@_/_ --options "pcre:with_unicode_properties=True" --options "pcre:with_bzip2=False" --build pcre
  - conan remove "cegui/*" --force
  - conan create cegui worldforge/stable -pr default --build missing && conan create cegui worldforge/stable -pr default
  - conan remove "ogre/*" --force
  - conan create ogre worldforge/stable -pr default --build missing && conan create ogre worldforge/stable -pr default
  - conan upload "*" -r worldforge -c --all

