language: cpp
dist: xenial
osx_image: xcode8
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - ccache

cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
before_install:
  - PY_CMD=python
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools
  - $PY_CMD -m pip install --user conan
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=$PATH:/Users/travis/Library/Python/2.7/bin
      brew update
      brew install xz
      brew install ccache
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  - conan user
  - conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
script:
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" != "clang++" ]]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - |
    if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
      conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
    else
      echo "Could not find BinTray password and login name"
      exit 1
    fi
  - conan create alut worldforge/testing -pr default --build missing && conan upload "alut/*@worldforge/testing" -r worldforge -c --all
  - conan create freeimage worldforge/testing -pr default --build missing && conan upload "freeimage/*@worldforge/testing" -r worldforge -c --all
  - conan create libxdg-basedir worldforge/testing -pr default --build missing && conan upload "libxdg-basedir/*@worldforge/testing" -r worldforge -c --all
  - conan create lua worldforge/testing -pr default --build missing && conan upload "lua/*@worldforge/testing" -r worldforge -c --all
  - conan create tolua++ worldforge/testing -pr default --build missing && conan upload "tolua++/*@worldforge/testing" -r worldforge -c --all
  - conan create cegui worldforge/testing -pr default --build missing && conan upload "cegui/*@worldforge/testing" -r worldforge -c --all
  - conan create ogre worldforge/testing -pr default --build missing && conan upload "ogre/*@worldforge/testing" -r worldforge -c --all
