language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode10.2
      compiler: clang

addons:
  apt:
    packages:
      - ccache
      - python3-pip
      - libgl1-mesa-dev
      - libxrandr-dev
      - libxaw7-dev
  homebrew:
    packages:
      - xz
      - ccache
      - python3
      
cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
before_install:
  - sudo pip3 install --upgrade pip wheel setuptools jinja2
  - sudo pip3 install --upgrade conan
  - conan --version
  - conan user
  - conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan
script:
  - set -e
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" != "clang++" ]]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - |
    if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
      conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
    else
      echo "Could not find BinTray password and login name"
      exit 1
    fi
  - conan remove "sigc++/*" --force
  - conan create sigc++ worldforge/stable -pr default --build missing && conan create sigc++ worldforge/stable -pr default && conan upload "sigc++/*@worldforge/stable" -r worldforge -c --all
  - conan remove "libcurl/*" --force
  - conan create libcurl worldforge/stable -pr default --build missing && conan create libcurl worldforge/stable -pr default && conan upload "libcurl/*@worldforge/stable" -r worldforge -c --all
  - conan remove "tinyxml/*" --force
  - conan create tinyxml worldforge/stable -pr default --build missing && conan create tinyxml worldforge/stable -pr default && conan upload "tinyxml/*@worldforge/stable" -r worldforge -c --all
  - conan remove "bullet3/*" --force
  - conan create bullet3 worldforge/stable -pr default --build missing && conan create bullet3 worldforge/stable -pr default && conan upload "bullet3/*@worldforge/stable" -r worldforge -c --all
  - conan remove "alut/*" --force
  - conan create alut worldforge/stable -pr default --build missing && conan create alut worldforge/stable -pr default && conan upload "alut/*@worldforge/stable" -r worldforge -c --all
  - conan remove "freeimage/*" --force
  - conan create freeimage worldforge/stable -pr default --build missing && conan create freeimage worldforge/stable -pr default && conan upload "freeimage/*@worldforge/stable" -r worldforge -c --all
  - conan remove "sdl2/*" --force
  - conan create sdl2 worldforge/stable -pr default --build missing && conan create sdl2 worldforge/stable -pr default && conan upload "sdl2/*@worldforge/stable" -r worldforge -c --all
  - conan remove "libxdg-basedir/*" --force
  - conan create libxdg-basedir worldforge/stable -pr default --build missing && conan create libxdg-basedir worldforge/stable -pr default && conan upload "libxdg-basedir/*@worldforge/stable" -r worldforge -c --all
  - conan remove "lua/*" --force
  - conan create lua worldforge/stable -pr default --build missing && conan create lua worldforge/stable -pr default && conan upload "lua/*@worldforge/stable" -r worldforge -c --all
  - conan remove "tolua++/*" --force
  - conan create tolua++ worldforge/stable -pr default --build missing && conan create tolua++ worldforge/stable -pr default && conan upload "tolua++/*@worldforge/stable" -r worldforge -c --all
  - conan remove "pcre/*" --force
  - conan install pcre/8.44@_/_ --options "pcre:with_unicode_properties=True" --options "pcre:with_bzip2=False" --build pcre && conan upload "pcre/8.44" -r worldforge -c --all
  - conan remove "cegui/*" --force
  - conan create cegui worldforge/stable -pr default --build missing && conan create cegui worldforge/stable -pr default && conan upload "cegui/*@worldforge/stable" -r worldforge -c --all
  - conan remove "ogre/*" --force
  - conan create ogre worldforge/stable -pr default --build missing && conan create ogre worldforge/stable -pr default && conan upload "ogre/*@worldforge/stable" -r worldforge -c --all
