language: cpp
dist: xenial
osx_image: xcode10.2
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - ccache
      - python3-pip
      - doxygen
      - graphviz
      - libgl1-mesa-dev
      - libxrandr-dev
      - libxaw7-dev
      - rsync
  homebrew:
    packages:
      - xz
      - ccache
      - python3
      - rsync

cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
      - $HOME/build/worldforge/ember/build/media-0.8.0
before_install:
  - sudo pip3 install --upgrade pip wheel setuptools
  - sudo pip3 install conan
  - conan user
  - conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan
script:
  - mkdir -p build && cd build
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" != "clang++" ]]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - conan install .. -pr default --build=missing
  - mkdir -p ~/install/usr
  - cmake -DCMAKE_INSTALL_PREFIX=~/install/usr ..
  - make media-download
  - make -j2
  - make -j2 check
  - if [ "$TRAVIS_OS_NAME" != "osx" -a "$CC" == "gcc" ]; then make dox; fi
  - make install
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CC" == "gcc" ]]; then
      ln -s ~/install/usr/share/icons/hicolor/64x64/apps/ember.png ~/install/
      ln -s ~/install/usr/share/applications/org.worldforge.ember.desktop ~/install/
      ln -s ~/install/ember.png ~/install/.DirIcon
      curl https://github.com/AppImage/AppImageKit/releases/download/12/AppRun-x86_64 > ~/install/AppRun
      chmod a+x ~/install/AppRun
      curl -L https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage > appimagetool-x86_64.AppImage
      chmod a+x appimagetool-x86_64.AppImage
      ./appimagetool-x86_64.AppImage -n ~/install
    fi
deploy:
  provider: bintray
  file: $HOME/build/worldforge/ember/build/bintray.json
  edge: true # opt in to dpl v2
  on:
    branch: master
    condition: $TRAVIS_OS_NAME != "osx" && $CC == "gcc"