language: cpp
dist: xenial
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - PY_CMD=python3
  - $PY_CMD --version
  - $PY_CMD -m ensurepip --default-pip
  # Install conan
  - $PY_CMD -m pip install --user --upgrade conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
script:
  - conan create tools/conan worldforge/testing --build missing
