os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  # Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
script:
  - conan create tools/conan worldforge/testing --build missing
