language: cpp
dist: xenial
osx_image: xcode10.2
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - ccache
      - python3-pip
      - doxygen
      - graphviz
      - libgl1-mesa-dev
      - libxrandr-dev
      - libxaw7-dev
  homebrew:
    packages:
      - xz
      - ccache
      - python3

cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
before_install:
  - sudo pip3 install --upgrade pip wheel setuptools
  - sudo pip3 install conan
  - conan user
  - conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan
script:
  - mkdir build && cd build
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" != "clang++" ]]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - conan install .. -pr default --build=missing
  - cmake ..
  - make
  - make check
  - if [ "$TRAVIS_OS_NAME" != "osx" -a "$CC" == "gcc" ]; then make dox; fi
