version: 1.0.{build}
  platform:
    - x64

  install:
    - cmmd: echo "Downloading conan..."
    - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
    - cmmd: pip.exe install conan
    - cmmd: conan user # Create the conan data directory
    - cmmd: conan --version
    - cmmd: conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan

  build_script:
    - cmmd: mkdir build
    - cmmd: cd build
    - cmmd: conan install ../tools/conan
    - cmmd: cmake -DBUILD_TESTING=ON ..
    - cmmd: cmake --build . --config Release

  test_script:
    - cmmd: ctest
