name: cyphesis
base: core22
version: git
title: Cyphesis MMORPG server
summary: Server for Worldforge MMORPGs
description: |
    A server for the Worldforge MMORPG system.
    Run this to host your own online game. It includes a complete
    physics based simulation with powerful online editing capabilities.
grade: devel
confinement: strict
license: GPL-2.0

apps:
    cyphesis:
        #daemon: simple
        command: bin/cyphesis --cyphesis:confdir=$SNAP/etc --cyphesis:vardir=$SNAP_USER_COMMON --cyphesis:directory=$SNAP/share --cyphesis:autoimport=$SNAP/share/worldforge/worlds/deeds/braga/world.xml --cyphesis:bindir=$SNAP/bin
        #listen-stream: "[::]:6767"
        plugs:
            - network
            - network-bind
    cypasswd:
        command: bin/cypasswd --cyphesis:confdir=$SNAP/etc --cyphesis:vardir=$SNAP_USER_COMMON --cyphesis:directory=$SNAP/share --cyphesis:autoimport=$SNAP/share/worldforge/worlds/deeds/braga/world.xml --cyphesis:bindir=$SNAP/bin
    cycmd:
        command: bin/cycmd --cyphesis:confdir=$SNAP/etc --cyphesis:vardir=$SNAP_USER_COMMON --cyphesis:directory=$SNAP/share --cyphesis:autoimport=$SNAP/share/worldforge/worlds/deeds/braga/world.xml --cyphesis:bindir=$SNAP/bin
    cydb:
        command: bin/cydb --cyphesis:confdir=$SNAP/etc --cyphesis:vardir=$SNAP_USER_COMMON --cyphesis:directory=$SNAP/share --cyphesis:autoimport=$SNAP/share/worldforge/worlds/deeds/braga/world.xml --cyphesis:bindir=$SNAP/bin
    cyaiclient:
        command: bin/cyaiclient --cyphesis:confdir=$SNAP/etc --cyphesis:vardir=$SNAP_USER_COMMON --cyphesis:directory=$SNAP/share --cyphesis:autoimport=$SNAP/share/worldforge/worlds/deeds/braga/world.xml --cyphesis:bindir=$SNAP/bin

parts:
    wfmath:
        source: https://github.com/worldforge/wfmath.git
        plugin: cmake
        build-packages:
            - g++

    atlas:
        source: https://github.com/worldforge/atlas-cpp.git
        plugin: cmake
        build-packages:
            - g++

    varconf:
        source: https://github.com/worldforge/varconf.git
        plugin: cmake
        build-packages:
            - g++
            - libsigc++-2.0-dev
        stage-packages:
            - libsigc++-2.0

    mercator:
        source: https://github.com/worldforge/mercator.git
        plugin: cmake
        build-packages:
            - g++
        after:
            - wfmath
    worlds:
        source: https://github.com/worldforge/worlds.git
        plugin: cmake

    media:
        build-packages:
            - rsync
            - curl
        override-pull: |
            #rsync -rtzu --include='*.mesh' --include='*/' --exclude='*' amber.worldforge.org::ember-media/ember-media-0.8.0/media/assets $SNAPCRAFT_PART_SRC/assets
            cd $SNAPCRAFT_PART_SRC
            curl -L https://amber.worldforge.org/ember/media/ember-media-0.8.0.tar.xz -o $SNAPCRAFT_PART_SRC/ember-media-0.8.0.tar.xz
            tar -xJf $SNAPCRAFT_PART_SRC/ember-media-0.8.0.tar.xz
        override-stage: |
            mkdir -p $SNAPCRAFT_STAGE/share/cyphesis
            cp -a $SNAPCRAFT_PART_SRC/ember-media-0.8.0/media/assets $SNAPCRAFT_STAGE/share/cyphesis
        override-prime: |
            mkdir -p $SNAPCRAFT_PRIME/share/cyphesis
            cp -a $SNAPCRAFT_STAGE/share/cyphesis/assets $SNAPCRAFT_PRIME/share/cyphesis
        plugin: nil

    cyphesis:
        source: .
        plugin: cmake
        build-packages:
            - python3-dev
            - libsqlite3-dev
            - libgcrypt-dev
            - libbullet-dev
            - libxdg-basedir-dev
            - libreadline-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - g++
        stage-packages:
            - libboost-filesystem1.74.0
            - libboost-system1.74.0
            - libbullet3.06
            - libpython3.10
            - libsigc++-2.0-0v5
            - libxdg-basedir1
        after:
            - media
            - atlas
            - varconf
            - mercator
            - worlds
