name: Build all

on:
  push:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # This makes it correctly use C++11 API on GCC by default.
  CONAN_V2_MODE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_SCM_TO_CONANDATA: 1
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022,macos-11, macos-12 ]

    steps:
      - uses: actions/checkout@v3

      - name: Fix paths
        shell: bash
        #Include all paths for Linux, Windows and MacOS. These will be used in all the steps that follow.
        run: echo ~/.local/bin:/Users/runner/Library/Python/3.11/bin:/c/Users/runneradmin/AppData/Roaming/Python/Python37/Scripts:/c/Users/runneradmin/AppData/Roaming/Python/Python39/Scripts:$PATH >> $GITHUB_PATH

      - name: Install autotools
        shell: bash
        run: |
          if [[ "$ImageOS" == macos* ]]; then
            brew install autoconf automake
          fi

      - name: Install Conan
        shell: bash
        run: |
          pip3 install pip wheel setuptools
          pip3 install --user conan
          conan --version
          conan user
          conan remote add worldforge https://artifactory.ogenvik.org/artifactory/api/conan/conan
          conan profile new default --detect

      - name: Build artifacts
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
            conan remove "sigc++/*" --force
            conan install ./sigc++ -g deploy --build missing && conan create ./sigc++ worldforge/stable -pr default
            conan remove "libxdg-basedir/*" --force
            conan install ./libxdg-basedir -g deploy --build missing && conan create ./libxdg-basedir worldforge/stable -pr default
            conan remove "pcre/*" --force
            conan install pcre/8.45@_/_ --options "pcre:with_unicode_properties=True" --options "pcre:with_bzip2=False" --build missing
            conan remove "cegui/*" --force
            conan install ./cegui -g deploy --build missing && conan create ./cegui worldforge/stable -pr default
            conan remove "ogre/*" --force
            conan install ./ogre -g deploy --build missing && conan create ./ogre worldforge/stable -pr default

            conan user --clean
            conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
            conan upload "*" -r worldforge -c --all
          fi
