name: Build all

on:
  push:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # This makes it correctly use C++11 API on GCC by default.
  CONAN_V2_MODE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_SCM_TO_CONANDATA: 1
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install autotools
        shell: bash
        run: |
          if [[ "$ImageOS" == "macos1015" ]]; then
            brew install autoconf automake
          fi

      - name: Install Conan
        shell: bash
        run: |
          export PATH=~/.local/bin:$PATH
          if [[ "$ImageOS" == "win19" ]]; then
            pip3 install --user --upgrade pip wheel setuptools
            pip3 install --user --upgrade conan
            echo "Adjusting path to include local Pip installed packages."
            export PATH="${PATH}:/c/Users/runneradmin/AppData/Roaming/Python/Python37/Scripts"
          else
            pip3 install --upgrade pip wheel setuptools
            pip3 install --upgrade conan
          fi
          conan --version
          conan user
          conan remote add worldforge https://artifactory.ogenvik.org/artifactory/api/conan/conan
          conan profile new default --detect

      - name: Build artifacts
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
            export PATH=~/.local/bin:$PATH
            if [[ "$ImageOS" == "win19" ]]; then
              export PATH="${PATH}:/c/Users/runneradmin/AppData/Roaming/Python/Python37/Scripts"
            fi

            conan remove "freeimage/*" --force
            conan install ./freeimage -g deploy --build missing && conan create ./freeimage worldforge/stable -pr default
            conan remove "sigc++/*" --force
            conan install ./sigc++ -g deploy --build missing && conan create ./sigc++ worldforge/stable -pr default
            conan remove "alut/*" --force
            conan install ./alut -g deploy --build missing && conan create ./alut worldforge/stable -pr default
            conan remove "sdl2/*" --force
            conan install ./sdl2 -g deploy --build missing && conan create ./sdl2 worldforge/stable -pr default
            conan remove "libxdg-basedir/*" --force
            conan install ./libxdg-basedir -g deploy --build missing && conan create ./libxdg-basedir worldforge/stable -pr default
            conan remove "lua/*" --force
            conan install ./lua -g deploy --build missing && conan create ./lua worldforge/stable -pr default
            conan remove "tolua++/*" --force
            conan install ./tolua++ -g deploy --build missing && conan create ./tolua++ worldforge/stable -pr default
            conan remove "pcre/*" --force
            conan install pcre/8.44@_/_ --options "pcre:with_unicode_properties=True" --options "pcre:with_bzip2=False" --build pcre
            conan remove "cegui/*" --force
            conan install ./cegui -g deploy --build missing && conan create ./cegui worldforge/stable -pr default
            conan remove "ogre/*" --force
            conan install ./ogre -g deploy --build missing && conan create ./ogre worldforge/stable -pr default
            if [[ "$ImageOS" != "win19" ]]; then
              conan remove "libgpg-error/*" --force
              conan install ./libgpg-error -g deploy --build missing && conan create ./libgpg-error worldforge/stable -pr default
              conan remove "libgcrypt/*" --force
              conan install ./libgcrypt -g deploy --build missing && conan create ./libgcrypt worldforge/stable -pr default
            fi

            conan user --clean
            conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
            conan upload "*" -r worldforge -c --all
          fi
